framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'admin@vodoucollector.fr'
#            recipients: [ 'foo@example.com', 'bar@example.com' ]
        headers:
            From: 'VodouCollector <admin@vodoucollector.fr>'
#            Bcc: 'baz@example.com'
#            X-Custom-Header: 'foobar'
